# Weights & Biases configuration
WANDB_MODE: "online" # Change to "online" for logging and include appropriate ENTITY and PROJECT arguments
ENTITY: "maytusp"
PROJECT: "Craftax-Coop-Symbolic"
RUN_NAME: "IPPO - RNN"

# Environment configuration
ENV_NAME: "Craftax-Coop-Symbolic" # Can be changed to "Craftax-Coop-Symbolic", "Craftax-Coop-Pixels", "Craftax-MA-Symbolic", "Craftax-MA-Pixels"

# Model parameters
ALG_NAME: "ippo-rnn"
GRU_HIDDEN_DIM: 512
FC_DIM_SIZE: 128
ACTIVATION: "tanh"

# Training parameters
TOTAL_TIMESTEPS: 1_000_000_000
NUM_ENVS: 1024
NUM_STEPS: 64
NUM_MINIBATCHES: 8
UPDATE_EPOCHS: 4
GAE_LAMBDA: 0.8
GAMMA: 0.99
CLIP_EPS: 0.2
SCALE_CLIP_EPS: false
ENT_COEF: 0.01
VF_COEF: 0.5
ANNEAL_LR: true
LR: 2e-4
MAX_GRAD_NORM: 1.0
LR_WARMUP: 0.0
REW_SHAPING_HORIZON: 1_000_000

# Seed configuration
NUM_SEEDS: 1
SEED: 0
